import React, { useState, useEffect, useRef } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { LayoutDashboard, Tent, FileText, Image as ImageIcon, Users, LogOut, KeyRound, Droplet, Download, MessageCircle, FileBadge, CheckCircle, Clock } from 'lucide-react';
import organizerService from '../../services/organizerService';
import ShareModal from '../../components/ShareModal';
import WAStatus from '../../components/WAStatus';
import jsPDF from 'jspdf';
import 'jspdf-autotable';
import html2canvas from 'html2canvas';

const Reports = () => {
  const [reportData, setReportData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [shareModal, setShareModal] = useState({ isOpen: false, type: null, camp: null, title: '' });
  const certificateRef = useRef(null);
  const [certData, setCertData] = useState(null); // to temporarily hold data for cert generation
  const [isSidebarOpen, setIsSidebarOpen] = useState(false);

  const user = JSON.parse(localStorage.getItem('user')) || {};
  const navigate = useNavigate();

  useEffect(() => {
    const fetchReports = async () => {
      try {
        const data = await organizerService.getReports();

        if (data.success) {
          setReportData(data);
        }
      } catch (err) {
        console.error("Error fetching reports", err);
      } finally {
        setLoading(false);
      }
    };
    fetchReports();
  }, []);

  const handleLogout = () => {
    localStorage.removeItem('organizer-token');
    localStorage.removeItem('user');
    navigate('/organizer-login');
  };

  const getBloodGroupColor = (bg) => {
    if (bg.includes('A+ ') || bg === 'A+' || bg === 'A-') return 'bg-[#FCEBEB] text-[#A32D2D]';
    if (bg === 'B+' || bg === 'B-') return 'bg-[#E1F5EE] text-[#085041]';
    if (bg === 'O+' || bg === 'O-') return 'bg-[#FAEEDA] text-[#633806]';
    if (bg === 'AB+' || bg === 'AB-') return 'bg-[#EEEDFE] text-[#3C3489]';
    return 'bg-gray-100 text-gray-600';
  };

  // PDF Generation - Individual Camp
  const generateCampReportPDF = (camp) => {
    const doc = new jsPDF();
    const dateStr = new Date(camp.date).toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' });

    // Header
    doc.setFontSize(22);
    doc.setTextColor(226, 75, 74); // #E24B4A
    doc.text("Raktdaan", 14, 22);

    doc.setFontSize(16);
    doc.setTextColor(40, 40, 40);
    doc.text("Camp Report", 14, 32);

    // Camp Details Box
    doc.setDrawColor(200, 200, 200);
    doc.setFillColor(250, 250, 250);
    doc.roundedRect(14, 40, 182, 35, 3, 3, 'FD');

    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("Camp Name:", 20, 50);
    doc.setFont("helvetica", "normal");
    doc.text(camp.title, 60, 50);

    doc.setFont("helvetica", "bold");
    doc.text("Date:", 20, 58);
    doc.setFont("helvetica", "normal");
    doc.text(dateStr, 60, 58);

    doc.setFont("helvetica", "bold");
    doc.text("Venue:", 20, 66);
    doc.setFont("helvetica", "normal");
    doc.text(`${camp.venue}, ${camp.city}`, 60, 66);

    // Impact Summary Box
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("Impact Summary", 14, 88);

    doc.autoTable({
      startY: 92,
      head: [['Metric', 'Value']],
      body: [
        ['Total Donors Attended', camp.stats.donorsAttended],
        ['Total Units Collected', camp.stats.unitsCollected],
        ['Lives Saved', camp.stats.livesSaved],
        ['Attendance Rate', `${camp.stats.attendancePercent}%`]
      ],
      theme: 'grid',
      headStyles: { fillColor: [226, 75, 74] },
    });

    // Blood Groups
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("Blood Group Breakdown", 14, doc.lastAutoTable.finalY + 15);

    const bgRows = [];
    let totalBGCount = 0;
    Object.keys(camp.stats.bloodGroupBreakdown).forEach(bg => {
      totalBGCount += camp.stats.bloodGroupBreakdown[bg];
    });

    Object.keys(camp.stats.bloodGroupBreakdown).forEach(bg => {
      const count = camp.stats.bloodGroupBreakdown[bg];
      if (count > 0) {
        const percent = ((count / totalBGCount) * 100).toFixed(1);
        bgRows.push([bg, count, `${percent}%`]);
      }
    });

    doc.autoTable({
      startY: doc.lastAutoTable.finalY + 20,
      head: [['Blood Group', 'Count', 'Percentage']],
      body: bgRows,
      theme: 'striped',
      headStyles: { fillColor: [28, 28, 40] } // #1C1C28
    });

    // Footer
    const pageHeight = doc.internal.pageSize.height;
    doc.setFontSize(10);
    doc.setTextColor(150, 150, 150);
    doc.text(`Generated by Raktdaan · raktdaan.online · ${new Date().toLocaleDateString()}`, 14, pageHeight - 10);

    const filenameDate = new Date(camp.date).toISOString().split('T')[0];
    doc.save(`report_${camp.title.replace(/\s+/g, '_')}_${filenameDate}.pdf`);
  };

  // PDF Generation - Overall Report
  const generateOverallReportPDF = () => {
    if (!reportData) return;
    const doc = new jsPDF();

    // Header
    doc.setFontSize(22);
    doc.setTextColor(226, 75, 74);
    doc.text("Raktdaan — Overall Camp Report", 14, 22);

    doc.setFontSize(12);
    doc.setTextColor(80, 80, 80);
    doc.text(`Organizer: ${user.name || 'Personal'}`, 14, 32);
    doc.text(`Generated: ${new Date().toLocaleDateString()}`, 14, 38);

    // Overall Totals
    doc.autoTable({
      startY: 45,
      head: [['Total Camps Organized', 'Total Donors', 'Total Units', 'Total Lives Saved']],
      body: [[
        reportData.overall.completedCamps,
        reportData.overall.totalDonors,
        reportData.overall.totalUnits,
        reportData.overall.totalLivesSaved
      ]],
      theme: 'grid',
      headStyles: { fillColor: [226, 75, 74], halign: 'center' },
      bodyStyles: { halign: 'center', fontSize: 14, fontStyle: 'bold' }
    });

    // Camp-wise Summary Table
    doc.setFontSize(14);
    doc.setTextColor(40, 40, 40);
    doc.text("Camp-wise Summary", 14, doc.lastAutoTable.finalY + 15);

    const campRows = reportData.camps
      .filter(c => c.status === 'completed')
      .map(c => [
        c.title,
        new Date(c.date).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' }),
        c.stats.donorsAttended,
        c.stats.unitsCollected,
        c.stats.livesSaved
      ]);

    doc.autoTable({
      startY: doc.lastAutoTable.finalY + 20,
      head: [['Camp Name', 'Date', 'Donors', 'Units', 'Lives']],
      body: campRows,
      theme: 'striped',
      headStyles: { fillColor: [28, 28, 40] }
    });

    // Footer
    const pageHeight = doc.internal.pageSize.height;
    doc.setFontSize(10);
    doc.setTextColor(150, 150, 150);
    doc.text("Generated by Raktdaan", 14, pageHeight - 10);

    const filenameDate = new Date().toISOString().split('T')[0];
    doc.save(`overall_report_${filenameDate}.pdf`);
  };

  // WhatsApp Sharing Logic
  const handleShareOverall = async (phone) => {
    if (!reportData) return;
    try {
      const data = await organizerService.shareReport({
        phone,
        totalCamps: reportData.overall.completedCamps,
        totalDonors: reportData.overall.totalDonors,
        totalUnits: reportData.overall.totalUnits,
        totalLives: reportData.overall.totalLivesSaved
      });
      if (!data.success) alert('There was a problem sending the WhatsApp message');
    } catch (err) {
      alert('Error: ' + err.message);
    }
  };

  const handleShareCamp = async (phone, camp) => {
    try {
      const data = await organizerService.shareCamp(camp.campId, phone);
      if (!data.success) alert('There was a problem sending the WhatsApp message.');
    } catch (err) {
      alert('Error: ' + err.message);
    }
  };

  // Generate Donation Certificate
  const generateCertificate = (camp) => {
    setCertData({
      campTitle: camp.title,
      date: new Date(camp.date).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }),
      organizerName: user.name || 'Raktdaan Team',
      donorsCount: camp.stats.donorsAttended,
      unitsCount: camp.stats.unitsCollected
    });

    setTimeout(async () => {
      if (certificateRef.current) {
        try {
          const canvas = await html2canvas(certificateRef.current, {
            scale: 2, // higher quality
            useCORS: true
          });
          const imgData = canvas.toDataURL('image/png');
          const pdf = new jsPDF('landscape', 'mm', 'a4');
          const pdfWidth = pdf.internal.pageSize.getWidth();
          const pdfHeight = pdf.internal.pageSize.getHeight();

          pdf.addImage(imgData, 'PNG', 0, 0, pdfWidth, pdfHeight);
          pdf.save(`Certificate_${camp.title.replace(/\s+/g, '_')}.pdf`);
          setCertData(null); // hide it again
        } catch (err) {
          console.error("Error generating certificate", err);
          setCertData(null);
        }
      }
    }, 500); // 500ms should be enough for DOM to paint
  };

  return (
    <div className="min-h-screen bg-[#FDFBF7] flex flex-col md:flex-row font-sans relative">

      {/* MOBILE HEADER */}
      <div className="md:hidden flex items-center justify-between bg-[#1C1C28] text-white p-4 fixed top-0 left-0 right-0 z-50 border-b border-white/5 shadow-md">
        <div className="flex items-center gap-2">
          <div className="bg-red-500 rounded-full p-1.5"><Droplet className="w-4 h-4 text-white" /></div>
          <span className="font-bold text-lg">Raktdaan</span>
        </div>
        <button onClick={() => setIsSidebarOpen(!isSidebarOpen)} className="p-2 hover:bg-white/10 rounded-lg text-white transition-colors">
          <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M4 6h16M4 12h16M4 18h16" />
          </svg>
        </button>
      </div>

      {/* MOBILE BACKDROP OVERLAY */}
      {isSidebarOpen && (
        <div onClick={() => setIsSidebarOpen(false)} className="md:hidden fixed inset-0 bg-black/55 z-30 transition-opacity" />
      )}

      {/* SIDEBAR */}
      <aside className={`fixed top-0 left-0 h-screen w-64 bg-[#1C1C28] text-gray-300 flex flex-col z-40 transition-transform duration-300 ${isSidebarOpen ? 'translate-x-0' : '-translate-x-full md:translate-x-0'}`}>
        <div className="p-5 pb-2">
          <div className="flex items-center justify-between gap-2.5 mb-6">
            <div className="flex items-center gap-2.5">
              <div className="bg-red-500 rounded-full p-1.5"><Droplet className="w-4 h-4 text-white" /></div>
              <div>
                <h1 className="text-white font-bold text-lg leading-tight">Raktdaan</h1>
                <p className="text-[10px] text-gray-400">Organizer Panel</p>
              </div>
            </div>
            {/* Close button for mobile */}
            <button onClick={() => setIsSidebarOpen(false)} className="md:hidden text-gray-400 hover:text-white p-1 rounded-lg hover:bg-white/5 transition-colors">
              <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
          </div>
          <p className="text-[10px] font-semibold tracking-wider text-gray-500 mb-3 px-2">MAIN</p>
        </div>

        <nav className="flex-1 px-3 space-y-1">
          <Link to="/organizer-dashboard/dashboard" onClick={() => setIsSidebarOpen(false)} className="w-full flex items-center gap-2.5 px-3 py-2.5 rounded-xl font-medium text-sm transition text-gray-400 hover:text-white hover:bg-white/5">
            <LayoutDashboard className="w-4 h-4" /> Dashboard
          </Link>
          <Link to="/organizer-dashboard/my-camps" onClick={() => setIsSidebarOpen(false)} className="w-full flex items-center gap-2.5 px-3 py-2.5 rounded-xl font-medium text-sm transition text-gray-400 hover:text-white hover:bg-white/5">
            <Tent className="w-4 h-4" /> My Camps
          </Link>
          <Link to="/organizer-dashboard/registrations" onClick={() => setIsSidebarOpen(false)} className="w-full flex items-center gap-2.5 px-3 py-2.5 rounded-xl font-medium text-sm transition text-gray-400 hover:text-white hover:bg-white/5">
            <Users className="w-4 h-4" /> Registrations
          </Link>
          <Link to="/organizer-dashboard/reports" onClick={() => setIsSidebarOpen(false)} className="w-full flex items-center gap-2.5 px-3 py-2.5 rounded-xl font-medium text-sm transition bg-[#E74C3C] text-white shadow-sm">
            <FileText className="w-4 h-4" /> Reports
          </Link>
          <Link to="/organizer-dashboard/gallery" onClick={() => setIsSidebarOpen(false)} className="w-full flex items-center gap-2.5 px-3 py-2.5 rounded-xl font-medium text-sm transition text-gray-400 hover:text-white hover:bg-white/5">
            <ImageIcon className="w-4 h-4" /> Gallery
          </Link>
        </nav>

        <div className="p-3 border-t border-white/10 mt-auto">
          <Link to="/organizer/change-password" onClick={() => setIsSidebarOpen(false)} className="w-full flex items-center gap-2.5 hover:bg-white/5 px-3 py-2 rounded-xl transition text-gray-400 hover:text-white text-sm mb-1.5">
            <KeyRound className="w-4 h-4" />
            <span className="font-medium">Change Password</span>
          </Link>
          <button onClick={handleLogout} className="w-full flex items-center justify-between hover:bg-white/5 px-3 py-2 rounded-xl transition group">
            <div className="flex items-center gap-2.5 text-left">
              <div className="bg-red-500/20 text-red-500 font-bold w-8 h-8 rounded-full flex items-center justify-center text-xs">
                {user.name ? user.name.charAt(0).toUpperCase() : 'O'}
              </div>
              <div>
                <p className="text-white text-xs font-semibold truncate w-24">{user.name || 'Organizer'}</p>
                <p className="text-[10px] text-gray-500">Personal</p>
              </div>
            </div>
            <LogOut className="w-4 h-4 text-gray-500 group-hover:text-red-400 transition" />
          </button>
        </div>
      </aside>

      {/* MAIN CONTENT */}
      <main className="flex-1 p-6 pt-24 md:pt-10 w-full md:w-[calc(100%-16rem)] md:ml-64">
        <div className="max-w-6xl mx-auto space-y-8">

          {/* SECTION 1 - HEADER ROW */}
          <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
            <div>
              <h2 className="text-2xl font-medium text-gray-900 flex items-center gap-4">Reports <WAStatus /></h2>
              <p className="text-sm text-gray-500 mt-1">Tumhare saare camps ka summary</p>
            </div>
            <div className="flex flex-col sm:flex-row items-stretch sm:items-center gap-3 w-full md:w-auto">
              <button
                onClick={generateOverallReportPDF}
                disabled={loading || !reportData || reportData.overall.completedCamps === 0}
                className="flex items-center justify-center gap-2 border border-gray-300 bg-white hover:bg-gray-50 text-gray-700 px-5 py-2.5 rounded-xl font-medium transition shadow-sm disabled:opacity-50"
              >
                <Download className="w-4 h-4" /> Download PDF
              </button>
              <button
                onClick={() => setShareModal({ isOpen: true, type: 'overall', title: 'Saare camps ka impact report share karein' })}
                disabled={loading || !reportData}
                className="flex items-center justify-center gap-2 bg-[#25D366] hover:bg-[#1DA851] text-white px-5 py-2.5 rounded-xl font-medium transition shadow-sm disabled:opacity-50"
              >
                <MessageCircle className="w-4 h-4" /> Share report
              </button>
            </div>
          </div>

          {loading ? (
            <div className="py-20 text-center text-gray-500">Loading reports...</div>
          ) : !reportData ? (
            <div className="py-20 text-center text-gray-500">Failed to load reports.</div>
          ) : (
            <>
              {/* SECTION 2 - OVERALL IMPACT BANNER */}
              <div className="bg-[#E24B4A] rounded-xl p-[14px] md:p-[16px] text-white shadow-md">
                <p className="text-xs uppercase font-bold tracking-wider opacity-80 mb-4">Overall impact — all camps</p>
                <div className="grid grid-cols-2 md:grid-cols-4 gap-6">
                  <div>
                    <p className="text-4xl font-bold leading-none mb-1">{reportData.overall.completedCamps}</p>
                    <p className="text-sm opacity-90 font-medium">Total camps</p>
                  </div>
                  <div>
                    <p className="text-4xl font-bold leading-none mb-1">{reportData.overall.totalDonors}</p>
                    <p className="text-sm opacity-90 font-medium">Total donors</p>
                  </div>
                  <div>
                    <p className="text-4xl font-bold leading-none mb-1">{reportData.overall.totalUnits}</p>
                    <p className="text-sm opacity-90 font-medium">Units collected</p>
                  </div>
                  <div>
                    <p className="text-4xl font-bold leading-none mb-1">{reportData.overall.totalLivesSaved}</p>
                    <p className="text-sm opacity-90 font-medium">Lives saved</p>
                  </div>
                </div>
              </div>

              {/* SECTION 3 - CAMP WISE REPORTS LABEL */}
              <h3 className="text-xs font-bold text-gray-500 uppercase tracking-wider mb-2 pt-4">Camp-wise reports</h3>

              {/* SECTION 4 - CAMP CARDS */}
              <div className="space-y-6">
                {reportData.camps.map(camp => {
                  if (camp.status !== 'completed') {
                    // UPCOMING CAMP CARD — with real registration data
                    return (
                      <div key={camp.campId} className="bg-white rounded-2xl p-6 border border-gray-200 shadow-sm">
                        <div className="flex flex-col md:flex-row md:items-start justify-between gap-4 mb-4">
                          <div className="flex items-start gap-4">
                            <div className="bg-red-50 border border-red-100 text-red-600 rounded-xl w-16 h-16 flex flex-col items-center justify-center shrink-0">
                              <span className="text-xl font-bold leading-none">{new Date(camp.date).getDate()}</span>
                              <span className="text-[10px] font-bold uppercase mt-1">{new Date(camp.date).toLocaleString('en-US', { month: 'short' })} '{new Date(camp.date).getFullYear().toString().slice(2)}</span>
                            </div>
                            <div>
                              <h4 className="text-lg font-bold text-gray-900 mb-0.5">{camp.title}</h4>
                              <p className="text-sm text-gray-500 font-medium">{camp.venue}, {camp.city}</p>
                            </div>
                          </div>
                          <span className="bg-amber-100 text-amber-800 text-xs font-bold px-3 py-1 rounded-full flex items-center gap-1.5 self-start">
                            <Clock className="w-3.5 h-3.5" /> Upcoming
                          </span>
                        </div>

                        {/* Stats for upcoming camp */}
                        <div className="grid grid-cols-3 gap-3">
                          <div className="bg-[#FCEBEB] p-3 rounded-xl border border-red-100 text-center">
                            <p className="text-xs font-bold text-gray-500 uppercase mb-1">Registered</p>
                            <p className="text-2xl font-bold text-[#A32D2D]">{camp.totalRegistered || 0}</p>
                          </div>
                          <div className="bg-[#FAEEDA] p-3 rounded-xl border border-amber-100 text-center">
                            <p className="text-xs font-bold text-gray-500 uppercase mb-1">Slots Left</p>
                            <p className="text-2xl font-bold text-[#633806]">{camp.slotsLeft ?? (camp.totalSlots || 100)}</p>
                          </div>
                          <div className="bg-[#E1F5EE] p-3 rounded-xl border border-teal-100 text-center">
                            <p className="text-xs font-bold text-gray-500 uppercase mb-1">Total Slots</p>
                            <p className="text-2xl font-bold text-[#085041]">{camp.totalSlots || 100}</p>
                          </div>
                        </div>

                        {/* Blood group breakdown if any */}
                        {camp.stats && Object.values(camp.stats.bloodGroupBreakdown).some(v => v > 0) && (
                          <div className="mt-4">
                            <p className="text-xs font-bold text-gray-500 uppercase mb-2">Blood groups registered</p>
                            <div className="flex flex-wrap gap-2">
                              {Object.keys(camp.stats.bloodGroupBreakdown).map(bg => {
                                const count = camp.stats.bloodGroupBreakdown[bg];
                                if (count === 0) return null;
                                return (
                                  <span key={bg} className={`px-3 py-1.5 rounded-lg text-sm font-bold flex items-center gap-1.5 ${getBloodGroupColor(bg)}`}>
                                    {bg} <span className="opacity-50">·</span> {count}
                                  </span>
                                );
                              })}
                            </div>
                          </div>
                        )}

                        {/* Progress bar */}
                        {camp.totalSlots > 0 && (
                          <div className="mt-4">
                            <div className="flex justify-between text-xs text-gray-500 mb-1">
                              <span>{camp.totalRegistered || 0} / {camp.totalSlots} slots filled</span>
                              <span>{Math.round(((camp.totalRegistered || 0) / camp.totalSlots) * 100)}%</span>
                            </div>
                            <div className="w-full bg-gray-100 h-2 rounded-full overflow-hidden">
                              <div className="bg-[#E24B4A] h-full rounded-full" style={{ width: `${Math.min(100, ((camp.totalRegistered || 0) / camp.totalSlots) * 100)}%` }} />
                            </div>
                          </div>
                        )}
                      </div>
                    );
                  }

                  // COMPLETED CAMP CARD
                  return (
                    <div key={camp.campId} className="bg-white rounded-2xl p-6 border border-gray-200 shadow-sm">
                      {/* Card header */}
                      <div className="flex flex-col md:flex-row md:items-start justify-between gap-4 mb-6">
                        <div className="flex items-start gap-4">
                          <div className="bg-[#E1F5EE] border border-[#A5DCCC] text-[#0F6E56] rounded-xl w-16 h-16 flex flex-col items-center justify-center shrink-0">
                            <span className="text-xl font-bold leading-none">{new Date(camp.date).getDate()}</span>
                            <span className="text-[10px] font-bold uppercase mt-1">{new Date(camp.date).toLocaleString('en-US', { month: 'short' })} '{new Date(camp.date).getFullYear().toString().slice(2)}</span>
                          </div>
                          <div>
                            <h4 className="text-lg font-bold text-gray-900 mb-0.5">{camp.title}</h4>
                            <p className="text-sm text-gray-500 font-medium">{camp.venue}, {camp.city}</p>
                          </div>
                        </div>
                        <div className="flex flex-col items-start md:items-end gap-2 shrink-0 w-full md:w-auto">
                          <span className="bg-[#E1F5EE] text-[#0F6E56] text-xs font-bold px-3 py-1 rounded-full flex items-center gap-1.5 self-start md:self-end">
                            <CheckCircle className="w-3.5 h-3.5" /> Completed
                          </span>
                          <div className="flex items-center gap-2 w-full md:w-auto mt-2 md:mt-0">
                            <button
                              onClick={() => setShareModal({ isOpen: true, type: 'camp', camp: camp, title: `Share report for ${camp.title}` })}
                              className="p-2 border border-gray-200 rounded-lg text-gray-500 hover:text-[#25D366] hover:bg-gray-50 transition"
                              title="Share on WhatsApp"
                            >
                              <MessageCircle className="w-4 h-4" />
                            </button>
                            <button
                              onClick={() => generateCampReportPDF(camp)}
                              className="flex-1 md:flex-none flex items-center justify-center gap-2 border border-gray-200 rounded-lg px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50 transition"
                            >
                              <Download className="w-4 h-4" /> Download PDF
                            </button>
                          </div>
                        </div>
                      </div>

                      {/* Stats grid */}
                      <div className="grid grid-cols-2 md:grid-cols-4 gap-3 mb-6">
                        <div className="bg-[#FCEBEB] p-3 rounded-xl border border-red-100">
                          <p className="text-xs font-bold text-gray-500 uppercase mb-1">Donors attended</p>
                          <p className="text-2xl font-bold text-[#A32D2D]">{camp.stats.donorsAttended}</p>
                        </div>
                        <div className="bg-[#E1F5EE] p-3 rounded-xl border border-teal-100">
                          <p className="text-xs font-bold text-gray-500 uppercase mb-1">Units collected</p>
                          <p className="text-2xl font-bold text-[#085041]">{camp.stats.unitsCollected}</p>
                        </div>
                        <div className="bg-[#EEEDFE] p-3 rounded-xl border border-purple-100">
                          <p className="text-xs font-bold text-gray-500 uppercase mb-1">Lives saved</p>
                          <p className="text-2xl font-bold text-[#3C3489]">{camp.stats.livesSaved}</p>
                        </div>
                        <div className="bg-[#FAEEDA] p-3 rounded-xl border border-amber-100">
                          <p className="text-xs font-bold text-gray-500 uppercase mb-1">Attendance %</p>
                          <p className="text-2xl font-bold text-[#633806]">{camp.stats.attendancePercent}%</p>
                        </div>
                      </div>

                      {/* Blood groups breakdown */}
                      <div className="mb-6">
                        <p className="text-xs font-bold text-gray-500 uppercase mb-3">Blood groups collected</p>
                        <div className="flex flex-wrap gap-2">
                          {Object.keys(camp.stats.bloodGroupBreakdown).map(bg => {
                            const count = camp.stats.bloodGroupBreakdown[bg];
                            if (count === 0) return null;
                            return (
                              <span key={bg} className={`px-3 py-1.5 rounded-lg text-sm font-bold flex items-center gap-1.5 ${getBloodGroupColor(bg)}`}>
                                {bg} <span className="opacity-50">·</span> {count}
                              </span>
                            );
                          })}
                        </div>
                      </div>

                      {/* Certificate section */}
                      {camp.hasCertificate && (
                        <div className="bg-[#E1F5EE] border border-[#A5DCCC] rounded-xl p-4 flex flex-col sm:flex-row items-center justify-between gap-4">
                          <div className="flex items-center gap-3">
                            <div className="bg-white p-2 rounded-full text-[#0F6E56]">
                              <FileBadge className="w-5 h-5" />
                            </div>
                            <p className="text-sm font-bold text-[#0F6E56]">Organizer certificate available hai</p>
                          </div>
                          <button
                            onClick={() => downloadCertificate(camp)}
                            className="w-full sm:w-auto bg-[#0F6E56] hover:bg-[#0A4A3A] text-white px-5 py-2 rounded-lg text-sm font-bold transition flex items-center justify-center gap-2 shadow-sm"
                          >
                            <Download className="w-4 h-4" /> Download
                          </button>
                        </div>
                      )}
                    </div>
                  );
                })}

                {reportData.camps.length === 0 && (
                  <div className="bg-white p-10 text-center rounded-2xl border border-gray-200">
                    <p className="text-gray-500 font-medium">Aapne abhi tak koi camp organize nahi kiya hai.</p>
                  </div>
                )}
              </div>
            </>
          )}
        </div>
      </main>

      {/* HIDDEN CERTIFICATE COMPONENT FOR HTML2CANVAS */}
      {certData && (
        <div style={{ position: 'absolute', top: '-9999px', left: '-9999px' }}>
          <div
            ref={certificateRef}
            style={{
              width: '1122px',
              height: '793px', // A4 Landscape roughly
              backgroundColor: '#ffffff',
              padding: '40px',
              boxSizing: 'border-box'
            }}
          >
            <div style={{
              border: '10px solid #E24B4A',
              height: '100%',
              padding: '60px',
              display: 'flex',
              flexDirection: 'column',
              alignItems: 'center',
              textAlign: 'center',
              position: 'relative'
            }}>
              {/* Background watermark or pattern can be added here */}
              <div style={{ marginBottom: '30px' }}>
                <Droplet size={60} color="#E24B4A" />
                <h1 style={{ fontSize: '32px', color: '#E24B4A', margin: '10px 0 0', fontWeight: 'bold' }}>Raktdaan</h1>
              </div>

              <h2 style={{ fontSize: '50px', color: '#1a1a2e', textTransform: 'uppercase', letterSpacing: '2px', marginBottom: '40px', fontWeight: 'bold' }}>
                Certificate of Appreciation
              </h2>

              <p style={{ fontSize: '24px', color: '#555', marginBottom: '20px' }}>
                This is to certify that
              </p>

              <h3 style={{ fontSize: '48px', color: '#E24B4A', marginBottom: '20px', fontFamily: 'serif', borderBottom: '2px solid #E24B4A', display: 'inline-block', paddingBottom: '10px' }}>
                {user.name || 'Organizer'}
              </h3>

              <p style={{ fontSize: '24px', color: '#555', marginBottom: '30px' }}>
                has successfully organized a Blood Donation Camp
              </p>

              <div style={{ backgroundColor: '#f9f9f9', padding: '20px 40px', borderRadius: '10px', marginBottom: '40px' }}>
                <p style={{ fontSize: '28px', color: '#1a1a2e', fontWeight: 'bold', margin: '0 0 10px' }}>{certData.title}</p>
                <p style={{ fontSize: '20px', color: '#666', margin: '0' }}>{new Date(certData.date).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })} • {certData.venue}</p>
              </div>

              <p style={{ fontSize: '22px', color: '#333', fontWeight: 'bold' }}>
                {certData.stats.donorsAttended} Donors Attended • {certData.stats.unitsCollected} Units Collected • {certData.stats.livesSaved} Lives Saved
              </p>

              <div style={{ position: 'absolute', bottom: '60px', width: '100%', display: 'flex', justifyContent: 'space-around', padding: '0 60px', boxSizing: 'border-box' }}>
                <div>
                  <p style={{ borderTop: '2px solid #333', paddingTop: '10px', fontSize: '18px', color: '#333', fontWeight: 'bold' }}>Date</p>
                  <p style={{ fontSize: '18px', color: '#555' }}>{new Date().toLocaleDateString()}</p>
                </div>
                <div>
                  <div style={{ height: '40px', display: 'flex', alignItems: 'flex-end', justifyContent: 'center' }}>
                    <span style={{ fontFamily: 'cursive', fontSize: '28px', color: '#E24B4A' }}>Raktdaan Team</span>
                  </div>
                  <p style={{ borderTop: '2px solid #333', paddingTop: '10px', fontSize: '18px', color: '#333', fontWeight: 'bold' }}>Authorized Signature</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* SHARE MODAL */}
      <ShareModal
        isOpen={shareModal.isOpen}
        onClose={() => setShareModal({ isOpen: false, type: null, camp: null, title: '' })}
        title={shareModal.title}
        onSend={(phone) => {
          if (shareModal.type === 'overall') {
            return handleShareOverall(phone);
          } else if (shareModal.type === 'camp') {
            return handleShareCamp(phone, shareModal.camp);
          }
        }}
      />

    </div>
  );
};

export default Reports;
